POST https://learn.codeit.kr/api/link-service/users
Content-Type:application/json

{
    "name":"코드22잇32",
    "email":"codeit22@example.com",
    "password":"password"
}

###

POST https://learn.codeit.kr/api/link-service/auth/login
Content-Type:application/json

{
    "email":"khm@naver.com",
    "password":"sodds1346!"
}