import type { Metadata } from "next";
import "./globals.css";
import ToasterProvider from "./contexts/toasterProvider";
import { Normal } from "./types/types";
import { AuthProvider } from "./contexts/authProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={``}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}

function Providers({ children }: Normal) {
  return (
    <ToasterProvider>
      <AuthProvider>{children}</AuthProvider>
    </ToasterProvider>
  );
}
